### ISSUE TITLE
Impossible to get integration_time to 400ms and 800ms

### ISSUE THREAD

**Issue by BigTwoProduction** [octaprog7/veml7700#2]
Hello,

I see you micropython integration for VEML7700 great work.
But i see, i think some mistakes in this def.

` def _get_resolution(gain: int, integration_time: int) -> float:`

You check two times the same parametres for gain and integration_time you check again gain by range 4 or 6.
And even if a correct code by
 ` _ = _check_value(integration_time, range(6), f"Invalid als integration_time: {integration_time}")`

I can get by set `sol.set_config_als(0, 2, 0, False, False)` to 4 for 400ms and 5 for 800ms a working set_config_als.

`sol.set_config_als(0, 4, 0, False, False)`

Best regards,
Jordan.

**Comment by BigTwoProduction** [comment]
Hello @octaprog7,

I see your commit 78f01f37e841bbbf22217729e36cda9b76032b48
I've take your fix but the problem still exist.
But still impossible to get 400ms and 800ms.

I put this set config and power save mode settings:
`sol.set_config_als(3, 4, 0, False, False)`   
`sol.set_power_save_mode(False, 0)`

`Traceback (most recent call last):`
  `File "<stdin>", line 29, in <module>`
  `File "VEML7700/veml7700vishay.py", line 134, in get_illumination`
  `File "VEML7700/veml7700vishay.py", line 29, in _get_resolution`
`ValueError: object not in sequence`

For your information i'm using "Pi Pico W"
_MicroPython v1.20.0 on 2023-04-26; Raspberry Pi Pico W with RP2040_

By the way i think the method you use for return illumination (lux) is wrong.
According to the _Designing the VEML7700 Into an Application_ section _CALCULATING THE LUX LEVEL_ it's said "When using GAIN level 1/4 and 1/8 the correction formula should be used." and when the lux is >=1000 and corrective formula need to be used. Because there is non-linearity above 1000. I will open a new issues for this problem. 
Can you just confirm to me i'm right ?

You can find all of this information at this link [https://www.vishay.com/docs/84323/designingveml7700.pdf](https://www.vishay.com/docs/84323/designingveml7700.pdf)

**Comment by octaprog7** [comment]
No response to last commit. I'm closing this issue!
Regarding the behavior of nonlinearity and correction formulas, I can say the following. I think it is wrong to use correction formulas in software that should only read data from the sensor!
Users of this module can use any correction formulas that they can implement!
